modLoader = "javafml"
loaderVersion = "[43,)"
license = "Tkt"
[[mods]]
modId = "kron"
version = "${file.jarVersion}"
displayName = "Kron"
displayURL = "https://vyxs.fr"
authors = "Vyxs & golden_apple1993"
displayTest="MATCH_VERSION"
description = '''
Super mod who add many things
'''

[[dependencies.kron]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kron]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"